### PR TITLE
Fix/params can be 0

### PR DESCRIPTION
**Pull request by wouterlucas**
There is no reason why ThunderJS should make assumptions on what the params value can (or can not) be. I.e. if we'd like to send 'params': 0 or 'params': false - we should be able to do so without constraints.

### CODE REVIEW

**Review by michielvandergeest — CHANGES_REQUESTED** [review]
LGTM. Passing `0` as params should be valid as well I guess (and that indeed won't work now). Not sure why the original conditional has been made more complex. Can't remember anymore if there was a specific reason for doing that or not ... 🤷🏻‍♂️

Minor change request: before merging we just need to be sure to bump the version of the package.

**Comment by wouterlucas** [comment]
Yep @nunofaria that is the exact same issue :) 

This should allow to send params: 0, params: false. I don't know if it will allow to send Params: '', but I can add a test case and figure that out.

**Comment by wouterlucas** [comment]
Hi @nunofaria just added a test case for '' and false, both seem to work as expected. Let me know if you have any further concerns.

@michielvandergeest I can't remember why that was put in there anymore either, looks like a wrong assumption or wishful thinking that went wrong. Bumped the package to v1.2.5 as requested.

**Review by michielvandergeest — APPROVED** [review]

**Comment by nunofaria** [comment]
Hi @wouterlucas, meanwhile these changes got merged and we were able to test them out in our solution and ran into some issues:

`params !== undefined ? (body.params = params) : null;`

We have several use cases where we make some `get` requests that do not require any parameters passed along. The way we do this, in our solution currently, is by passing empty objects over to ThunderJS in those scenarios.
Previously, ThunderJS would ignore those empty objects and actually not assign `body.params` with `{}`, but after this modification, ThunderJS is sending this empty object in the message, over to the socket.
Then, on the Thunder framework below, that is causing undesired issues, which are then returned as error messages.

All this said, we were wondering if these latest changes may also cause issues such as these, on other solutions.

On our end, we ended up fixing these use cases with the following update to your previous code:

https://github.com/nunofaria/ThunderJS/blob/36-falsy-param-support/src/api/makeBody.js

`params === 0` being added to the OR clauses at the beginning of the code block:

```
  // check if params exist
  params || params === false || params === 0
    ? // params is not an empty object, or it is a boolean or a number
      typeof params === 'object' && Object.keys(params).length === 0
      ? null
      : (body.params = params)
    : null
```

Based on all of this, do you think it would make sense to ensure this added check on your fix as well?

**Comment by wouterlucas** [comment]
Hi @nunofaria - is there any reason to send empty objects over from JS? Sounds like that's the problem :) 
I rather like to keep ThunderJS as transparent as possible.

**Pull request merged**
